spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projeto_rpg
    username: root
    password: Kaguya10.
  jpa:
    hibernate:
      ddl-auto: update